spring:
  datasource:
    username: root
    password: 123qweASD

#spring.datasource.url = jdbc:mysql://localhost:3306/users_db
#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

myapp:
  version: 1.1